improve play and setwall to work with xdg user dirs

diff --git a/setwall b/setwall
--- a/setwall
+++ b/setwall
@@ -1,18 +1,34 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
-#ls "$HOME"/Pictures/wallpapers/* | dmenu -b -l 10 -fn  "Hack Regular Nerd Font Complete" | xargs -I {} feh --bg-fill --no-fehbg "{}"
-#sel=$(find "$HOME"/Pictures/wallpapers/* | dmenu -b -l 10 -fn  "Hack Regular Nerd Font Complete")
-WALL_DIR=Pictures/wallpapers
-WALL_DIR2='$HOME'/$WALL_DIR
-sel=$WALL_DIR2/$(ls "$HOME/$WALL_DIR" | dmenu -i -l 10 -fn  "Hack Regular Nerd Font Complete")
-# otherwise sel is set to first item and it is ugly
-# and I need to add this dreary / at the end because otherwise it
-# does not match
-# TODO: make trailing slash independent
-if [ "$sel" = "$WALL_DIR2"/ ];
+font_name="Hack Regular Nerd Font Complete"
+lines=10
+
+wall_dir=$(xdg-user-dir WALLPAPERS)
+wall_dir_alt=$(echo $wall_dir | sed s,$HOME,'$HOME',)
+
+sel=$(find "$wall_dir" -type f -print0 |
+	  # slow with sh -c but without basename did not work
+	  xargs -0 -I {} sh -c 'echo $(basename -a "{}")' |
+	  dmenu -i -l "$lines" -fn "$font_name")
+# TODO:
+# something to consider? sel=$(ffile "$wall_dir")
+
+if [ -z "$sel" ];
 then
-	exit 1
+    echo "Nothing was chosen"
+    exit 0
 fi
-feh --bg-fill --no-fehbg "$WALL_DIR"/$(basename $sel)
-prev=$(grep "WALLPAPER" "$XDG_CONFIG_HOME"/shell/variables | cut -d= -f2)
-sed -i "s,$prev,$sel,g" "$XDG_CONFIG_HOME"/shell/variables 
+
+echo $sel
+
+feh --bg-fill --no-fehbg "$wall_dir"/"$sel" || {
+    echo "Cannot set $sel as wallpaper";
+    exit 1; }
+
+sel="$wall_dir_alt"/"$sel"
+
+# set in XDG_CONFIG_HOME/user-dirs.dirs
+env_var_file=$(xdg-user-dir SHVARS)
+
+prev=$(grep "WALLPAPER" "$env_var_file" | cut -d= -f2)
+sed -i "s,$prev,$sel,g" "$env_var_file"
